import {api,archiveUrl} from './api.mjs';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Plus,LockKey,EnvelopeSimple,BookOpen,Images,NotePencil,X,Heart,DownloadSimple,UploadSimple,SignOut,CaretLeft,CaretRight,SealCheck,Gift,Orange,Airplane,MusicNotes,BowlFood,HandHeart,PencilSimple,Trash} from '@phosphor-icons/react';
const navigation=[['home','档案'],['story','故事'],['photos','相册'],['letters','来信'],['records','未完待续']];
const categories=[['all','全部'],['travel','一起旅行'],['campus','校服写真'],['hanfu','汉服写真'],['snaps','日常']];
const vouchers=[['vc-orange','无条件投喂甜橙券','给祝晨剥一颗最甜的橙子。',Orange],['vc-hug','一键消气 · 捏捏脸券','暂停争吵，捏脸给抱抱。',HandHeart],['vc-hotpot','热气腾腾小火锅券','一起煮一顿热气腾腾的小火锅。',BowlFood],['vc-travel','目的地任选出行券','下一站旅行，目的地由祝晨指定。',Airplane],['vc-song','自创儿歌独家听众券','做你自创儿歌的专属听众。',MusicNotes]];
function OpenSiteLink(){return <a className="outline" href={archiveUrl} target="_blank" rel="noopener noreferrer">在浏览器中打开</a>;}
const recordUuid=()=>{if(crypto.randomUUID)return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const h=Array.from(bytes,v=>v.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);};
const send=(path,data,method='POST')=>api(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const media=r=>'/media/'+r.photo_key;
const date=r=>r.occurred_on||(r.created_at?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(r.created_at)):'');
function Body({text}){return <div className="prose">{text?.split(/\n\n+/).map((p,i)=><p key={i}>{p}</p>)}</div>;}
function Modal({label,children,onClose,wide=false}){const ref=useRef();useEffect(()=>{const before=document.activeElement;const key=e=>{if(e.key==='Escape'){onClose();return;}if(e.key==='Tab'){const els=[...ref.current.querySelectorAll('button,input,select,textarea,a[href]')].filter(n=>!n.disabled);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current.querySelector('button,input')?.focus();return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;before?.focus();};},[onClose]);return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={ref} role="dialog" aria-modal="true" aria-label={label} className={'dialog '+(wide?'wide':'')}><button type="button" className="close icon-button" onClick={onClose} aria-label="关闭"><X size={24}/></button>{children}</section></div>;}
function Frame({record,onClick,className='',eager=false}){if(!record)return null;return <button className={'photo-frame '+className} onClick={onClick} aria-label={'查看照片：'+record.title}><div className="photo-inner"><img src={media(record)} alt={record.title} loading={eager?'eager':'lazy'}/></div><div className="caption"><span>{record.place||record.title}</span><span>{record.occurred_on||record.id.replace('PH-','No. ')}</span></div></button>;}
function Composer({initial,onClose,onSave}){const [form,setForm]=useState(()=>({id:'USR-'+recordUuid(),type:'memory',title:'',body:'',place:'',author:'',category:'snaps',occurred_on:'',open_on:'',...initial}));const [file,setFile]=useState(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const editing=!!initial?.created_at;useEffect(()=>{if(!file)return;const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u);},[file]);const set=(k,v)=>setForm(f=>({...f,[k]:v}));async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(form.type==='photo'&&!editing){if(!file)throw new Error('先选一张照片吧。');const data=new FormData();for(const [k,v]of Object.entries(form))if(typeof v==='string')data.set(k,v);data.set('file',file);await api('/api/records',{method:'POST',body:data});}else await send(editing?'/api/records/'+encodeURIComponent(form.id):'/api/records',form,editing?'PATCH':'POST');await onSave();onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}
return <Modal label={editing?'编辑记录':'添加记录'} onClose={onClose}><div className="eyebrow">A NEW PAGE</div><h2>{editing?'再写得准确一点':'把这一刻留下来'}</h2><form onSubmit={submit} className="compose-form"><label>记录类型<select value={form.type} onChange={e=>set('type',e.target.value)} disabled={editing}><option value="photo">一张照片</option><option value="memory">一段回忆</option><option value="reply">一封回信</option><option value="future">未来记录 / 时间胶囊</option>{editing&&!['photo','memory','reply','future'].includes(form.type)&&<option value={form.type}>原有档案</option>}</select></label>{form.type==='photo'&&!editing&&<label className="upload-zone"><Images size={30}/><span>{file?file.name:'选择照片'}</span><small>JPG、PNG、WebP · 最大 15 MB</small><input aria-label="选择照片" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files[0]||null)}/>{preview&&<img className="upload-preview" src={preview} alt="准备上传的照片"/>}</label>}<label>标题<input maxLength={120} value={form.title} onChange={e=>set('title',e.target.value)} placeholder={form.type==='reply'?'给你的一封回信':'这一天，想记住什么'} required/></label><label>{form.type==='photo'?'照片旁的几句话':'正文'}<textarea maxLength={20000} rows={6} value={form.body} onChange={e=>set('body',e.target.value)} placeholder="慢慢写，不用写得很漂亮。" required={form.type!=='photo'}/></label><div className="form-row"><label>署名<input value={form.author} onChange={e=>set('author',e.target.value)} maxLength={40} placeholder="你的名字"/></label><label>发生日期（可留空）<input type="date" value={form.occurred_on} onChange={e=>set('occurred_on',e.target.value)}/></label></div>{form.type==='photo'&&<div className="form-row"><label>地点<input value={form.place} onChange={e=>set('place',e.target.value)} maxLength={100} placeholder="在哪里"/></label><label>分类<select value={form.category} onChange={e=>set('category',e.target.value)}>{categories.filter(([k])=>k!=='all').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>}{form.type==='future'&&<label>开启日期（可留空）<input type="date" value={form.open_on} onChange={e=>set('open_on',e.target.value)}/><small>设置后，正文会等到这一天才展示。</small></label>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'正在保存…':editing?'保存修改':'保存这一页'}</button></form></Modal>;}
export function App(){
const [authenticated,setAuthenticated]=useState(null),[records,setRecords]=useState([]),[preferences,setPreferences]=useState({}),[page,setPage]=useState('home'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[lastSync,setLastSync]=useState(''),[toast,setToast]=useState(''),[composer,setComposer]=useState(null),[lightbox,setLightbox]=useState(null),[letterOpen,setLetterOpen]=useState(false),[category,setCategory]=useState('all'),[slide,setSlide]=useState(0),[puffer,setPuffer]=useState(false),[deleteTarget,setDeleteTarget]=useState(null),[importBusy,setImportBusy]=useState(false),[prefBusy,setPrefBusy]=useState(false);
const importRef=useRef();
const notify=useCallback(m=>{setToast(m);},[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
const refresh=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const data=await api('/api/archive');setRecords(data.records);setPreferences(data.preferences);setError('');setLastSync(new Date().toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit'}));}catch(e){if(e.status===401){setAuthenticated(false);setRecords([]);setPreferences({});}else{setError(e.message);if(!silent)throw e;}}finally{setLoading(false);}},[]);
useEffect(()=>{api('/api/session').then(d=>setAuthenticated(d.authenticated)).catch(e=>setError(e.message));},[]);
useEffect(()=>{if(!authenticated)return;refresh().catch(()=>{});const focus=()=>refresh(true);const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh(true);},20000);window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[authenticated,refresh]);
useEffect(()=>{const context=document.modelContext;if(!context?.registerTool||!authenticated)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'start_archive_record',title:'准备添加记录',description:'打开照片、回信或记忆编辑框；不会立即保存。',inputSchema:{type:'object',properties:{type:{type:'string',enum:['photo','memory','reply','future']},title:{type:'string'},body:{type:'string'}},required:['type'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!['photo','memory','reply','future'].includes(input?.type)||Object.keys(input).some(k=>!['type','title','body'].includes(k))||[input.title,input.body].some(v=>v!==undefined&&typeof v!=='string'))throw new Error('记录格式不正确');setComposer(input);return {status:'draft_opened',type:input.type};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[authenticated]);
const byType=t=>records.filter(r=>r.type===t),photos=byType('photo'),stories=byType('story'),memories=byType('memory'),littles=byType('little'),letters=byType('letter'),replies=byType('reply'),futures=byType('future'),visiblePhotos=photos.filter(r=>category==='all'||r.category===category);
const heroPhotos=photos.length?[photos.find(r=>r.id==='PH-002')||photos[0],photos.find(r=>r.id==='PH-011')||photos[0],photos.find(r=>r.id==='PH-001')||photos[0]]:[];
const go=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'});};
async function pref(key,value){setPrefBusy(true);try{await send('/api/preferences',{key,value});setPreferences(p=>({...p,[key]:value}));return true;}catch(e){notify(e.message);return false;}finally{setPrefBusy(false);}}
async function logout(){try{await send('/api/logout',{});setAuthenticated(false);setRecords([]);setPreferences({});setPage('home');}catch(e){notify(e.message);}}
async function importBackup(e){const file=e.target.files[0];if(!file)return;setImportBusy(true);try{if(file.size>1024*1024)throw new Error('请选择 1 MB 以内的旧站 JSON 备份。');const data=JSON.parse(await file.text());const r=await send('/api/import',data);await refresh();notify('已导入 '+r.count+' 条记录。');}catch(e){notify(e instanceof SyntaxError?'这个文件不是有效的 JSON 备份。':e.message);}finally{setImportBusy(false);e.target.value='';}}
const saved=async()=>{await refresh();notify('已经存好了。换台设备也能看到。');};
const edit=r=>{setLightbox(null);setComposer(r);};
const actions=r=><div className="record-actions"><button className="text-button" onClick={()=>edit(r)} aria-label={'编辑 '+r.title}><PencilSimple size={17}/>编辑</button>{(r.id.startsWith('USR-')||r.id.startsWith('IMPORTED-'))&&<button className="text-button" onClick={()=>setDeleteTarget(r)} aria-label={'删除 '+r.title}><Trash size={17}/>删除</button>}</div>;
if(authenticated===null)return <main className="entrance"><div className="entry-card"><div className="eyebrow">OUR ARCHIVE</div><h1>未完待续</h1><p role="status">{error||'正在翻开这一页…'}</p>{error&&<div className="entry-recovery"><button className="outline" onClick={()=>window.location.reload()}>重试</button><OpenSiteLink/></div>}</div></main>;
if(!authenticated)return <Login onSuccess={()=>{setAuthenticated(true);setError('');}}/>;
return <><header className="site-header"><button className="brand" onClick={()=>go('home')}><span>未完待续</span><small>OUR ARCHIVE</small></button><div className="header-line"/><nav aria-label="档案栏目">{navigation.map(([id,label])=><button key={id} onClick={()=>go(id)} className={page===id?'active':''}>{label}</button>)}</nav><div className="header-line"/><button className="outline add-record" onClick={()=>setComposer({type:'memory'})}><Plus size={18}/>添加记录</button></header>
<main className="site-main">{error&&<div className="load-error" role="alert">{error}<button onClick={()=>refresh().catch(()=>{})}>重新读取</button></div>}{loading&&records.length===0?<div className="loading" role="status">正在取出我们的档案…</div>:<>
{page==='home'&&<><section className="hero"><div className="hero-text"><div className="eyebrow">PRIVATE COLLECTION</div><p className="hero-date">2020 — 至今</p><h1>未完<br/>待续</h1><span className="short-rule"/><p className="hero-intro">这里存了一些，<br className="desktop-break"/>关于你的东西。</p><button className="outline" onClick={()=>go('story')}><BookOpen size={18}/>翻开档案</button></div><div className="hero-picture"><Frame record={heroPhotos[slide]} onClick={()=>setLightbox(heroPhotos[slide])} eager className="hero-frame"/><div className="slide-controls"><button className="icon-button" aria-label="上一张合影" onClick={()=>setSlide((slide+2)%3)}><CaretLeft size={19}/></button><span>{String(slide+1).padStart(2,'0')} / 03</span><button className="icon-button" aria-label="下一张合影" onClick={()=>setSlide((slide+1)%3)}><CaretRight size={19}/></button></div></div></section>
<section className="home-second"><Frame record={photos.find(r=>r.id==='PH-011')||photos[0]} onClick={()=>setLightbox(photos.find(r=>r.id==='PH-011')||photos[0])} className="small-frame"/><div className="memory-preview"><div className="eyebrow">BETWEEN THE FRAMES</div><h2>那些没拍下来的瞬间</h2><span className="short-rule"/><p>{memories.find(r=>r.id==='MEM-002')?.body}</p><button className="text-button" onClick={()=>go('story')}>读一读这些回忆</button></div><button className="envelope-button" onClick={()=>setLetterOpen(true)} aria-label="拆开写给现在的你的信"><img src="/assets/ivory-envelope-burgundy-seal.webp" alt="暖白信封，酒红色火漆封缄"/><span className="envelope-label"><strong>写给现在的你</strong><small>给祝晨的一封信</small></span><span className="envelope-hint">轻触火漆，拆开这封信</span></button></section>
<section className="recent-section"><div className="section-heading"><div><div className="eyebrow">THE NEXT CHAPTER</div><h2>新添的几页</h2></div><button className="text-button" onClick={()=>go('records')}>继续写下去</button></div>{records.filter(r=>r.id.startsWith('USR-')).length?<div className="note-grid">{records.filter(r=>r.id.startsWith('USR-')).slice(-3).reverse().map(r=><article className="note-card" key={r.id}><div className="eyebrow">{date(r)} · {r.author||'我们'}</div><h3>{r.title}</h3>{r.type==='photo'?<Frame record={r} onClick={()=>setLightbox(r)}/>:<p>{r.sealed?'这页封缄到 '+r.open_on:r.body.slice(0,120)}</p>}</article>)}</div>:<div className="empty-inline"><p>下一张照片，下一次见面，下一件小事。</p><button className="outline" onClick={()=>setComposer({type:'memory'})}><Plus size={18}/>写下新的一页</button></div>}</section></>}
{page==='story'&&<><PageTitle kicker="OUR STORY" title="我们的故事" description="从最初相遇，到后来每一次重逢。"/><section className="story-timeline">{stories.map((r,i)=><article key={r.id}><span className="chapter-no">0{i+1}</span><div><div className="eyebrow">{r.category}</div><h2>{r.title}</h2><Body text={r.body}/>{actions(r)}</div></article>)}</section><section className="section-space"><div className="section-heading"><div><div className="eyebrow">UNPHOTOGRAPHED</div><h2>那些没拍下来的瞬间</h2></div><button className="outline" onClick={()=>setComposer({type:'memory'})}><Plus size={18}/>补一段回忆</button></div><div className="note-grid">{memories.map((r,i)=><article className="note-card" key={r.id}><span className="eyebrow">MEMORY {String(i+1).padStart(2,'0')}</span><h3>{r.title==='那些没有拍下来的瞬间'?'记得那一次':r.title}</h3><Body text={r.body}/>{actions(r)}</article>)}</div></section><section className="section-space little-section"><div className="eyebrow">THINGS ABOUT YOU</div><h2>关于你，我记住的小事</h2><div className="little-list">{littles.map((r,i)=><div key={r.id}><span>{String(i+1).padStart(2,'0')}</span><p>{r.body}</p><button className={'little-heart icon-button '+(preferences.hearts?.includes(r.id)?'liked':'')} disabled={prefBusy} aria-label={'记住小事 '+(i+1)} aria-pressed={!!preferences.hearts?.includes(r.id)} onClick={()=>pref('hearts',preferences.hearts?.includes(r.id)?preferences.hearts.filter(id=>id!==r.id):[...preferences.hearts||[],r.id])}><Heart size={18} weight={preferences.hearts?.includes(r.id)?'fill':'regular'}/></button></div>)}</div></section><section className="section-space"><div className="eyebrow">THE WAY WE ARE</div><h2>关于我们</h2><div className="note-grid">{[['good','开心的'],['hard','难过的'],['real','真实的']].map(([k,v])=><article className="note-card" key={k}><h3>{v}</h3>{byType('us').filter(r=>r.category===k).map(r=><p key={r.id}>{r.body}</p>)}</article>)}</div></section></>}
{page==='photos'&&<><PageTitle kicker="THE PHOTO ALBUM" title="一帧一帧，都是我们" description={`${photos.length} 张照片，留住那些一起走过的日子。`} action={<button className="outline" onClick={()=>setComposer({type:'photo'})}><Plus size={18}/>添加照片</button>}/><div className="filter-row" role="group" aria-label="照片分类">{categories.map(([k,v])=><button className={category===k?'selected':''} key={k} onClick={()=>setCategory(k)}>{v}</button>)}</div><div className="gallery">{visiblePhotos.map(r=><Frame key={r.id} record={r} onClick={()=>setLightbox(r)}/>)}</div>{visiblePhotos.length===0&&<p className="empty-inline">这个分类还没有照片，慢慢添。</p>}</>}
{page==='letters'&&<><PageTitle kicker="LETTERS TO YOU" title="有些话，想写给你" description="拆开一封信，也留下你的回信。" action={<button className="outline" onClick={()=>setComposer({type:'reply'})}><NotePencil size={18}/>写一封回信</button>}/><div className="letter-shelf"><button className="envelope-button large-envelope" onClick={()=>setLetterOpen(true)}><img src="/assets/ivory-envelope-burgundy-seal.webp" alt="火漆封缄的暖白信封"/><span className="envelope-label"><strong>写给现在的你</strong><small>给祝晨的一封信</small></span><span className="envelope-hint">轻触拆信</span></button><div><div className="eyebrow">TO YOU, ALWAYS</div><h2>一封很长的信</h2><p>有些话，当面说的时候总是说不好。<br/>所以，把它们放在这里。</p><button className="outline" onClick={()=>setLetterOpen(true)}><EnvelopeSimple size={19}/>拆开读一读</button></div></div><section className="section-space"><div className="section-heading"><h2>我们的回信</h2><span className="muted">{replies.length} 封</span></div>{replies.length?<div className="reply-list">{replies.map(r=><article className="reply-paper" key={r.id}><div className="eyebrow">{date(r)} · {r.author||'一封回信'}</div><h3>{r.title}</h3><Body text={r.body}/>{actions(r)}</article>)}</div>:<div className="empty-inline"><p>这里留一页空白，等你的回信。</p><button className="outline" onClick={()=>setComposer({type:'reply'})}>写给对方</button></div>}</section><section className="section-space"><div className="eyebrow">JUST FOR YOU</div><h2>祝晨专属 · 特权券</h2><div className="voucher-grid">{vouchers.map(([id,title,desc,Icon])=><article className="voucher" key={id}><Icon size={31} weight="light"/><h3>{title}</h3><p>{desc}</p><button className="text-button" disabled={prefBusy} onClick={async()=>{const count=(preferences.vouchers?.[id]||0)+1;if(await pref('vouchers',{...preferences.vouchers,[id]:count}))notify('记下了，等见面兑现。');}}>{preferences.vouchers?.[id]?`已兑换 ${preferences.vouchers[id]} 次 · 再兑换一次`:'兑换这张券'}</button></article>)}</div></section></>}
{page==='records'&&<><PageTitle kicker="TO BE CONTINUED" title="故事，还在往后写" description="记下一件小事，或给未来的我们留一封信。" action={<button className="outline" onClick={()=>setComposer({type:'future'})}><Plus size={18}/>添加未来记录</button>}/>{futures.length?<div className="note-grid">{[...futures].reverse().map(r=><article className={'note-card '+(r.sealed?'sealed':'')} key={r.id}><div className="eyebrow">{r.sealed?<><LockKey size={15}/> {r.open_on} 开启</>:date(r)}</div><h3>{r.title}</h3>{r.sealed?<p>这一页还在等它的日期。</p>:<><Body text={r.body}/><div className="muted">{r.author}</div>{actions(r)}</>}</article>)}</div>:<div className="empty-inline"><p>未来的第一页，还没有落笔。</p><button className="outline" onClick={()=>setComposer({type:'future'})}><NotePencil size={18}/>写给未来的我们</button></div>}<section className="section-space"><div className="eyebrow">A SMALL KEEPSAKE</div><h2>好好收着</h2><p className="muted">旧站的回信和未来记录，可以从原来的浏览器导出后带到这里。</p><div className="backup-actions"><button className="outline" disabled={importBusy} onClick={()=>importRef.current.click()}><UploadSimple size={18}/>{importBusy?'正在导入…':'导入旧站备份'}</button><a className="outline" href="/api/export" download><DownloadSimple size={18}/>导出文字记录</a></div><small className="backup-note">文字备份不包含照片文件；照片继续保存在相册里；封缄中的正文到期后才会导出。</small><input ref={importRef} type="file" accept="application/json,.json" hidden onChange={importBackup}/></section></>}
</>}</main>
<footer className="site-footer"><button className="puffer-trigger text-button" onClick={()=>setPuffer(true)}>致小河豚</button><span>我们的故事，未完待续。</span><div className="footer-right"><small aria-live="polite">{lastSync?'上次读取 '+lastSync:'等待读取'}</small><button className="icon-button" onClick={logout} aria-label="锁上档案"><SignOut size={20}/></button></div></footer>
{toast&&<div className="toast" role="status">{toast}</div>}
{composer&&<Composer initial={composer} onClose={()=>setComposer(null)} onSave={saved}/>}
{lightbox&&<Modal label={lightbox.title} onClose={()=>setLightbox(null)} wide><div className="lightbox"><img src={media(lightbox)} alt={lightbox.title}/><div className="lightbox-copy"><div className="eyebrow">{lightbox.place} {lightbox.occurred_on&&' · '+lightbox.occurred_on}</div><h2>{lightbox.title}</h2><Body text={lightbox.body}/><div className="lightbox-actions"><button className={'text-button '+(preferences.likes?.includes(lightbox.id)?'liked':'')} disabled={prefBusy} onClick={()=>pref('likes',preferences.likes?.includes(lightbox.id)?preferences.likes.filter(id=>id!==lightbox.id):[...preferences.likes||[],lightbox.id])}><Heart size={20} weight={preferences.likes?.includes(lightbox.id)?'fill':'regular'}/>喜欢这一张</button>{actions(lightbox)}</div><div className="lightbox-nav"><button className="outline" onClick={()=>setLightbox(photos[(photos.findIndex(r=>r.id===lightbox.id)+photos.length-1)%photos.length])}><CaretLeft size={18}/>上一张</button><button className="outline" onClick={()=>setLightbox(photos[(photos.findIndex(r=>r.id===lightbox.id)+1)%photos.length])}>下一张<CaretRight size={18}/></button></div></div></div></Modal>}
{letterOpen&&<Modal label="写给现在的你" onClose={()=>setLetterOpen(false)} wide><article className="letter-paper"><div className="eyebrow">A LETTER, JUST FOR YOU</div><h2>写给现在的你</h2><span className="short-rule"/>{letters.map(r=><Body key={r.id} text={r.body}/>)}<div className="letter-end"><span>未完待续</span><button className="outline" onClick={()=>{setLetterOpen(false);setComposer({type:'reply'});}}><NotePencil size={18}/>写一封回信</button></div></article></Modal>}
{puffer&&<Modal label="致小河豚" onClose={()=>setPuffer(false)}><div className="puffer-card"><div className="eyebrow">A LITTLE SECRET</div><h2>找到小河豚了</h2><Frame record={photos.find(r=>r.id==='PH-015')} onClick={()=>{setPuffer(false);setLightbox(photos.find(r=>r.id==='PH-015'));}}/><p>{littles.find(r=>r.id==='LT-010')?.body}</p><button className="outline" onClick={async()=>{if(await pref('fingerprint',true))notify('留下一枚小小的印记。');}} disabled={prefBusy}><SealCheck size={19}/>{preferences.fingerprint?'我们的印记还在':'留下我们的印记'}</button></div></Modal>}
{deleteTarget&&<Modal label="删除记录" onClose={()=>setDeleteTarget(null)}><h2>删除这一页？</h2><p>「{deleteTarget.title}」会从档案中移除。</p><div className="backup-actions"><button className="outline" onClick={()=>setDeleteTarget(null)}>再留着</button><button className="primary" onClick={async()=>{try{await send('/api/records/'+encodeURIComponent(deleteTarget.id),{},'DELETE');setDeleteTarget(null);setLightbox(null);await refresh();notify('已移除这一页。');}catch(e){notify(e.message);}}}>确认删除</button></div></Modal>}
</>;
}
function PageTitle({kicker,title,description,action}){return <div className="page-title"><div><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>;}
function Login({onSuccess}){const [password,setPassword]=useState(''),[remember,setRemember]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');async function login(e){e.preventDefault();setBusy(true);setError('');try{await send('/api/login',{password,remember});const state=await api('/api/session');if(!state.authenticated)throw new Error('浏览器没有保留登录状态，请在新标签页打开本站后重试。');setPassword('');onSuccess();}catch(e){setError(e.message);}finally{setBusy(false);}}return <main className="entrance"><div className="entry-card"><div className="eyebrow">OUR ARCHIVE · PRIVATE COLLECTION</div><h1>未完待续</h1><img className="entry-envelope" src="/assets/ivory-envelope-burgundy-seal.webp" alt="等待拆开的信封"/><p>有些故事，只想讲给你听。</p><form onSubmit={login}><label className="sr-only" htmlFor="archive-password">档案密码</label><div className="password-input"><LockKey size={20}/><input autoFocus id="archive-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="输入我们的密码" autoComplete="current-password" required maxLength={200}/></div><label className="checkbox"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>在这台设备记住我 30 天</label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'正在解锁…':'打开我们的档案'}</button></form>{(error||window.self!==window.top)&&<div className="entry-recovery"><OpenSiteLink/></div>}<small>2020 — 至今</small></div></main>;}
